my_first_dw_stream_project:
  outputs:
    prod:
      type: databricks
      catalog: workspace
      schema: dev_analytics
      host: dbc-f7a07339-6784.cloud.databricks.com
      # This routes queries smoothly past sign-up loops directly into your isolated protocol endpoint
      http_path: /sql/1.0/warehouses/c8d1eeaa14c5ef60
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"

      # 🚨 Memory Guard Protection: Limit to 1 thread to respect your M1 8GB RAM footprint
      threads: 1
  target: prod
